title: "V. Krishna Sameera"
description: "Personal Resume and Portfolio"
theme: minima

author: V. Krishna Sameera
email: krishnasameerav@gmail.com

minima:
  social_links:
    - email: krishnasameerav@gmail.com

# Enable relative links
permalink: pretty

