title: "V. Krishna Sameera - Resume"
description: "Personal Resume and Portfolio"
theme: jekyll-theme-cayman

# Optional settings
author: V. Krishna Sameera
email: krishnasameerav@gmail.com
show_downloads: false
google_analytics: 
